import type { Metadata } from "next";
import "./globals.css"; // <--- ADD THIS LINE
import { Rajdhani, Manrope } from "next/font/google";
import Header from "@/app/components/header";
import Footer from "@/app/components/footer";

const rajdhani = Rajdhani({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-rajdhani', // This defines the CSS variable
  display: 'swap',
});

const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope', // This defines the CSS variable
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Welcome to Insights",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Favicon links seem fine */}
      <link rel="icon" href="/favicon.ico" />
      <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
      <link rel="manifest" href="/site.webmanifest" />
      <body
        // Apply BOTH font variables to the body class
        // Set the default font family using Tailwind's utility class (font-manrope)
        className={`${rajdhani.variable} ${manrope.variable} font-manrope pb-8 `}
      >
         <Header/>
        {children}
        <Footer/>
        <p className="relative text-gray-600  w-screen text-center ">copyrights © Bromuno Outsight  2025</p>
      </body>
    </html>
  );
}
